[tool.poetry]
name = "Web crawler"
version = "0.1.0"
description = "Web crawler"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.0"
beautifulsoup4 = "^4.11.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"